name: random_password
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  random_password_generator: ^0.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.6
  flashy_tab_bar2: ^0.0.10
  google_fonts: ^6.2.1
  vibration: ^2.0.1
  password_strength_indicator: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true
